### ISSUE TITLE
config.h is missing version information

### ISSUE THREAD

**Issue by drscriptt** [SirWumpus/milter-clamc#1]
Hi,

I'm having trouble compiling milter-clamc as downloaded from GitHub.  I'm getting the following error when trying to compile:

```
gcc -DMILTER_BUILD=`cat BUILD_ID.TXT` -DMILTER_BUILD_STRING='"'`cat BUILD_ID.TXT`'"' \
  -I/usr/include/x86_64-pc-linux-gnu/db5.3   -Wall -Wno-unused -Wno-char-subscripts -I./../../include    -L/usr/include/lib   -L./../../lib -D_BUILT="\"`date +'%a, %d %b %Y %H:%M:%S %z'`\"" -o milter-clamc milter-clamc.c -lsnert  -lpthread -lmilter -lpthread -lsqlite3 -lm -ldb  -lpthread
milter-clamc.c:681:21: error: expected expression before ‘,’ token
  681 |         MILTER_MAJOR,
      |                     ^
make: *** [makefile:121: milter-clamc] Error 1
```
It seems as if the following maros don't have values in them:

- MILTER_MAJOR
- MILTER_MINOR
- MILTER_VERSION ""

I am able to successfully compile milter-clamc after populating values in those macros with values from VERSION in the makefile and BUILD_ID.TXT.

Changing config.h from this:
```
#define MILTER_MAJOR
#define MILTER_MINOR
#define MILTER_VERSION ""
```
to this:
```
#define MILTER_MAJOR 0
#define MILTER_MINOR 7
#define MILTER_VERSION "0.7.1"
```
allows me to build milter-clamc without any problems.

I don't know if I'm using the proper values (I patterned off of other milters for where they got their values) and I'm not set up to do a pull request.  So I hope that this issue report will suffice.

Thank you for all of your work and great software!

**Comment by SirWumpus** [comment]
I've build it successfully without issue.  Did you first build [libsnert](https://github.com/SirWumpus/libsnert#configuration--build)?  What was the ./configure summary for libsnert?  Once libsnert is built, then configure milter-clamc and make.

**Comment by SirWumpus** [comment]
> I'm not set up to do a pull request. 

You can download tarballs instead of cloning a repo, just need `curl(1)` or similar tool to download from GitHub:

* https://github.com/SirWumpus/libsnert/archive/refs/tags/v1.77.2.tar.gz
* https://github.com/SirWumpus/milter-clamc/archive/refs/tags/v0.7.1.tar.gz

**Comment by SirWumpus** [comment]
I cannot duplicate this issue.  I can only assume that somehow the builds were not in a clean state.  Try `make distclean; ./configure ...` for libsnert and milter-clamc.

**Comment by drscriptt** [comment]
> Did you first build libsnert?

Yes. 
```
lib% ./configure
...
LibSnert/1.77.2
Copyright 1996, 2023 by Anthony Howe. All rights reserved.

  Platform............: Linux gcc 13 2 1
  prefix..............: /usr/local
  datarootdir.........: ${prefix}/share
  Berkeley DB.........: 5.3 "-I/usr/include/x86_64-pc-linux-gnu/db5.3" "-L/usr/include/lib" "-ldb"
  Lua.................: "" "" "-lm"
  libev...............: "" "" ""
  OpenSSL.............: "" "" "-lssl -lcrypto"
  POSIX Semaphores....: "" "" ""
  POSIX Threads.......: "" "" "-lpthread"
  Sendmail libmilter..: "" "" "-lpthread -lmilter"
  SQLite3.............: "" "" "-lpthread -lsqlite3 -lm"
  Semaphore API.......: POSIX_API
  Shared Memory API...: POSIX_API
  CFLAGS..............: -Wall -Wno-unused -Wno-char-subscripts -I${top_srcdir}/../../include
  CPPFLAGS............: -I${top_srcdir}/../../include
  LDFLAGS.............: -L${top_srcdir}/../../lib
  LIBS................:
  NETWORK_LIBS........:
```
```
lib% make
...
***************************************************************
LibSnert 1.77.2 tools DONE
***************************************************************
lib% echo $?
0
```
Though I've run into an unexpected behavior when building libsnert.  I am planing on submitting a different issue about that.  But I am able to successfully build libsnert.
```
milter-clamc% ./configure
...
milter-clamc/..
Copyright 2006, 2012 by Anthony Howe. All rights reserved.

  Platform..............: Linux gcc
  LibSnert..............: yes
  --prefix..............: /usr/local
  --datadir.............: /usr/local/share
  --localstatedir.......: /var
  --exec_prefix.........: ${prefix}
  --sbindir.............: ${exec_prefix}/sbin
  --libexecdir..........: ${exec_prefix}/libexec
  --enable-run-user.....: milter
  --enable-run-group....: milter
  --enable-pid..........: /var/run/milter/milter-clamc.pid
  --enable-socket.......: /var/run/milter/milter-clamc.socket
  --enable-cache-file...: /var/cache/milter-clamc.db
  --enable-cache-type...: default
  --with-sendmail.......: /etc/mail
  CFLAGS................:  -Wall -Wno-unused -Wno-char-subscripts -I${top_srcdir}/../../include
  LDFLAGS...............:  -L${top_srcdir}/../../lib
  LIBS..................:  -lsnert
```
```
milter-clamc% make
gcc -DMILTER_BUILD=`cat BUILD_ID.TXT` -DMILTER_BUILD_STRING='"'`cat BUILD_ID.TXT`'"' \
  -I/usr/include/x86_64-pc-linux-gnu/db5.3   -Wall -Wno-unused -Wno-char-subscripts -I./../../include    -L/usr/include/lib   -L./../../lib -D_BUILT="\"`date +'%a, %d %b %Y %H:%M:%S %z'`\"" -o milter-clamc milter-clamc.c -lsnert  -lpthread -lmilter -lpthread -lsqlite3 -lm -ldb  -lpthread
milter-clamc.c:681:21: error: expected expression before ‘,’ token
  681 |         MILTER_MAJOR,
      |                     ^
make: *** [makefile:121: milter-clamc] Error 1
milter-clamc% echo $?
2
```
```
milter-clamc% cp config.h config.h.bak
```
```
milter-clamc% vi config.h
```
```
milter-clamc% make
gcc -DMILTER_BUILD=`cat BUILD_ID.TXT` -DMILTER_BUILD_STRING='"'`cat BUILD_ID.TXT`'"' \
  -I/usr/include/x86_64-pc-linux-gnu/db5.3   -Wall -Wno-unused -Wno-char-subscripts -I./../../include    -L/usr/include/lib   -L./../../lib -D_BUILT="\"`date +'%a, %d %b %Y %H:%M:%S %z'`\"" -o milter-clamc milter-clamc.c -lsnert  -lpthread -lmilter -lpthread -lsqlite3 -lm -ldb  -lpthread

***************************************************************
Build 0.7.1 DONE
***************************************************************
milter-clamc% echo $?
0
```
```
milter-clamc% diff config.h config.h.bak
15,17c15,17
< #define MILTER_MAJOR 0
< #define MILTER_MINOR 7.1
< #define MILTER_VERSION "0.7.1"
---
> #define MILTER_MAJOR
> #define MILTER_MINOR
> #define MILTER_VERSION ""
```
> You can download tarballs instead

I was referring to my current inability to submit the patch to you via GitHub, not that I was having a problem getting source files.

Aside:  Thank you for the URLs to download older tarballs without using `git`.

> I cannot duplicate this issue.

:-/

> I can only assume that somehow the builds were not in a clean state.

That is usually a safe assumption.  Though I've taken pains to make sure it wasn't problems I introduced.  I've done this by removing the entire com directory tree including the things are `git clone`d into.

> Try `make distclean; ./configure` ... for libsnert and milter-clamc.

After doing a `make distclean`, `autoconf`, `./configure`, and `make` for libsnert, here's the output of the same dance from milter-clamc

```
milter-clamc% make distclean && autoconf -f && ./configure && make
rm -f *.o milter-clamc *.exe milter-clamc.cf

***************************************************************
Clean DONE
***************************************************************

---------------------------------------------------------------
rm -f milter-clamc milter-clamc.md5 *.o *.obj *.tds *.log *.exe *.core
rm -f sample.mc startup.sh install.sh config.h makefile
rm -rf autom4te.cache config.status config.log configure.lineno configure~

***************************************************************
Distribution Clean /tmp/com/snert/src/milter-clamc DONE
***************************************************************

cat: ./VERSION.TXT: No such file or directory
platform is... Linux
checking for md5sum... /usr/bin/md5sum
checking for autoconf-2.69... no
checking for autoconf... /usr/bin/autoconf

milter-clamc/
Copyright 2006, 2012 by Anthony Howe. All rights reserved.


Generating files...

configure: creating ./config.status
config.status: creating manual.shtml
config.status: WARNING:  'manual.shtml.in' seems to ignore the --datarootdir setting
config.status: creating startup.sh
config.status: creating sample.mc
config.status: creating install.sh
config.status: WARNING:  'install.sh.in' seems to ignore the --datarootdir setting
config.status: creating makefile
config.status: creating config.h

milter-clamc/..
Copyright 2006, 2012 by Anthony Howe. All rights reserved.

  Platform..............: Linux gcc
  LibSnert..............: yes
  --prefix..............: /usr/local
  --datadir.............: /usr/local/share
  --localstatedir.......: /var
  --exec_prefix.........: ${prefix}
  --sbindir.............: ${exec_prefix}/sbin
  --libexecdir..........: ${exec_prefix}/libexec
  --enable-run-user.....: milter
  --enable-run-group....: milter
  --enable-pid..........: /var/run/milter/milter-clamc.pid
  --enable-socket.......: /var/run/milter/milter-clamc.socket
  --enable-cache-file...: /var/cache/milter-clamc.db
  --enable-cache-type...: default
  --with-sendmail.......: /etc/mail
  CFLAGS................:  -Wall -Wno-unused -Wno-char-subscripts -I${top_srcdir}/../../include
  LDFLAGS...............:  -L${top_srcdir}/../../lib
  LIBS..................:  -lsnert

gcc -DMILTER_BUILD=`cat BUILD_ID.TXT` -DMILTER_BUILD_STRING='"'`cat BUILD_ID.TXT`'"' \
  -I/usr/include/x86_64-pc-linux-gnu/db5.3   -Wall -Wno-unused -Wno-char-subscripts -I./../../include    -L/usr/include/lib   -L./../../lib -D_BUILT="\"`date +'%a, %d %b %Y %H:%M:%S %z'`\"" -o milter-clamc milter-clamc.c -lsnert  -lpthread -lmilter -lpthread -lsqlite3 -lm -ldb  -lpthread
milter-clamc.c:681:21: error: expected expression before ‘,’ token
  681 |         MILTER_MAJOR,
      |                     ^
make: *** [makefile:121: milter-clamc] Error 1
```
If I apply the aforementioned edit to config.h, then milter-clamc compiles just fine.

I think that I've spoken to all your comments.  Please let me know if you'd like anything else.  I don't know if something is preventing `autoconf` from populating the values in config.h or something else is not working as desired.

Thank you for your time and help.

**Comment by SirWumpus** [comment]
I was just about to ask for a `typescript` log, when your comment above appeared. It is most bizarre.

Hmm.

> milter-clamc/..
> Copyright 2006, 2012 by Anthony Howe. All rights reserved.

The configure script does see the values by the time the summary is written.  Notice the `/..`.

> cat: ./VERSION.TXT: No such file or directory

Oh! Frack!  I found it.  For some reason its still dependent on `VERSION.TXT`, which I think I was moving away from (and didnot include in the repo).  I of course still have the file laying about in my working directory, which is why I never saw the issue.

```
elf$ cat VERSION.TXT
0.7.0
```

So if you create a `VERSION.TXT` you won't need to twiddle the config.h.  Mean while I'll see what's what and fix it (I've either forgotten to the file or I moved away from it and did not update the configure script with a new scheme).

**Comment by drscriptt** [comment]
> I found it.

Cool!

I did a `make distclean` and created the VERSION.TXT file as you showed.

Now config.h has values, all be it 0.7.0 vs 0.7.1 which seem to be what comes out of the bottom of the `make` command.
```
milter-clamc% make distclean
rm -f *.o milter-clamc *.exe milter-clamc.cf

***************************************************************
Clean DONE
***************************************************************

---------------------------------------------------------------
rm -f milter-clamc milter-clamc.md5 *.o *.obj *.tds *.log *.exe *.core
rm -f sample.mc startup.sh install.sh config.h makefile
rm -rf autom4te.cache config.status config.log configure.lineno configure~

***************************************************************
Distribution Clean /tmp/com/snert/src/milter-clamc DONE
***************************************************************
```
```
milter-clamc% cat VERSION.TXT
0.7.0
```
```
milter-clamc% ./configure
platform is... Linux
checking for md5sum... /usr/bin/md5sum
checking for autoconf-2.69... no
checking for autoconf... /usr/bin/autoconf

milter-clamc/0.7.0
Copyright 2006, 2012 by Anthony Howe. All rights reserved.


Generating files...

configure: creating ./config.status
config.status: creating manual.shtml
config.status: WARNING:  'manual.shtml.in' seems to ignore the --datarootdir setting
config.status: creating startup.sh
config.status: creating sample.mc
config.status: creating install.sh
config.status: WARNING:  'install.sh.in' seems to ignore the --datarootdir setting
config.status: creating makefile
config.status: creating config.h

milter-clamc/0.7.0
Copyright 2006, 2012 by Anthony Howe. All rights reserved.

  Platform..............: Linux gcc
  LibSnert..............: yes
  --prefix..............: /usr/local
  --datadir.............: /usr/local/share
  --localstatedir.......: /var
  --exec_prefix.........: ${prefix}
  --sbindir.............: ${exec_prefix}/sbin
  --libexecdir..........: ${exec_prefix}/libexec
  --enable-run-user.....: milter
  --enable-run-group....: milter
  --enable-pid..........: /var/run/milter/milter-clamc.pid
  --enable-socket.......: /var/run/milter/milter-clamc.socket
  --enable-cache-file...: /var/cache/milter-clamc.db
  --enable-cache-type...: default
  --with-sendmail.......: /etc/mail
  CFLAGS................:  -Wall -Wno-unused -Wno-char-subscripts -I${top_srcdir}/../../include
  LDFLAGS...............:  -L${top_srcdir}/../../lib
  LIBS..................:  -lsnert
```
```
milter-clamc% make
gcc -DMILTER_BUILD=`cat BUILD_ID.TXT` -DMILTER_BUILD_STRING='"'`cat BUILD_ID.TXT`'"' \
  -I/usr/include/x86_64-pc-linux-gnu/db5.3   -Wall -Wno-unused -Wno-char-subscripts -I./../../include    -L/usr/include/lib   -L./../../lib -D_BUILT="\"`date +'%a, %d %b %Y %H:%M:%S %z'`\"" -o milter-clamc milter-clamc.c -lsnert  -lpthread -lmilter -lpthread -lsqlite3 -lm -ldb  -lpthread

***************************************************************
Build 0.7.1 DONE
***************************************************************
```
I believe you have found the root cause of the config.h is missing version information.

Thank you!!!

**Comment by SirWumpus** [comment]
I'll make it nice an purrty tonight or tomorrow.  Thanks for bearing with me and providing the extra info.

**Comment by drscriptt** [comment]
F.Y.I. I have created the two issues I alluded to on the libsnert repo.

- [SHA hash function name errors on lines 53 & 54 of mail/dkim-hash.c](https://github.com/SirWumpus/libsnert/issues/5)
- [Unexpected behavior while compiling libsnert](https://github.com/SirWumpus/libsnert/issues/6)

Thank you gain for your wonderful milters and all of your work SirWumpus!!!  :-D

**Comment by drscriptt** [comment]
> I'll make it nice an purrty tonight or tomorrow.

Cool.

> Thanks for bearing with me and providing the extra info.

You're quite welcome.

Thank you for your effort.

It behooves me to help you help me.  :-D

I had gotten past my immediate problems of compiling libsnert & milter-clamc on contemporary Gentoo system (manually).  So I was trying to provide feedback / my findings to help you and your users avoid the toe stubbing I had.

#teamEffort

**Comment by SirWumpus** [comment]
Side-buffet: The Bane of my software is tying to be portable across multiple OSes (*BSDs, Solaris, CentOS, AIX, HPUX, Linux's all with a different view of the file system layouts before they tried to standardise) with different locations for ~shite~ stuff like Berkeley DB (just look at SNERT_BERKELEY_DB in libsnert/acsite.m4 at the efforts).  This of course was back in the early noughts; I not revisited that code nor kept abreast of Linux changes; I develop on NetBSD and these days occasionally test on Rocky Linux.

Plug: You REALLY should look at BarricadeMX; it replaces all the milters with one filtering proxy.  You get SpamAss, ClamAV, Link (URI tests), plus a lot more, enable what you need / like.  With BMX you can support Sendmail, PostFix, Elm, Qmail (ewww), Exchange (barf), any MTA.  I run it on my server.  If you want a bit of a giggle `telnet mx.snert.org 25` to see the SMTP banner.

**Comment by SirWumpus** [comment]
BTW the SMTP banner is configurable.

**Comment by drscriptt** [comment]
> Side-buffet: The Bane of my software is tying to be portable across multiple OSes (*BSDs, Solaris, CentOS, AIX, HPUX, Linux's all with a different view of the file system layouts before they tried to standardise) with different locations for shite stuff like Berkeley DB (just look at SNERT_BERKELEY_DB in libsnert/acsite.m4 at the efforts). This of course was back in the early noughts; I not revisited that code nor kept abreast of Linux changes; I develop on NetBSD and these days occasionally test on Rocky Linux.

ACK

If there's anything that I can do to help, testing, etc., please let me know.  I have access to some (old) FreeBSD, Solaris 10 & 11, and can probably get access to more if you'd like some testing done.

I know someone that has a build farm that they use for their old MUMPS application, I bet she'd help me / us out with some testing on her build farm.

> Plug: You REALLY should look at BarricadeMX; it replaces all the milters with one filtering proxy. You get SpamAss, ClamAV, Link (URI tests), plus a lot more, enable what you need / like. With BMX you can support Sendmail, PostFix, Elm, Qmail (ewww), Exchange (barf), any MTA. I run it on my server. If you want a bit of a giggle telnet mx.snert.org 25 to see the SMTP banner.

I'll check it out.

I am quite fond of Sendmail plus milters.  I feel like it's very manual transmission / vi* hands on which I like.  I also don't know how well it an additional server would fit into my current minimalist infrastructure of low single digit VPSs / VMs.

**Comment by drscriptt** [comment]
> BTW the SMTP banner is configurable.

I like the multi-line SMTP greeting, that by itself will throw a lot of lesser quality non-RFC compliant SMTP stacks for a loop.

I also like the saying that you have in the multi-line SMTP greeting.

I'll keep my fingers in my pockets while lookenpeeping.

**Comment by SirWumpus** [comment]
> If there's anything that I can do to help, testing, etc., please let me know. I have access to some (old) FreeBSD, Solaris 10 & 11, and can probably get access to more if you'd like some testing done.
> 
> I know someone that has a build farm that they use for their old MUMPS application, I bet she'd help me / us out with some testing on her build farm.

Not sure if I want to go there; I have enough without making more work for myself.  Solaris is gone, old systems should still work fine; so too older FreeBSD, OpenBSD, NetBSD since I built on those.  Its the new stuff that sometimes changes.

> I am quite fond of Sendmail plus milters. I feel like it's very manual transmission / vi* hands on which I like. I also don't know how well it an additional server would fit into my current minimalist infrastructure of low single digit VPSs / VMs.

You don't necessarily need a new server to run it, just put it on the same MXes.  Also BarriacdeMX does not need a lot of resources.  BMX and run in old hardware and not drive the CPU high; it wasone of the pluses.  When I was partnered with FSL, they had a uni. in the UK (South Hampton?) that managed to go from 5 MXes to 3 after installing BMX and still have CPU to spare.  Another client, dropped Barracuda in favour of BMX cause they found it worked better and needed less support.  Anyway.

**Comment by SirWumpus** [comment]
> > BTW the SMTP banner is configurable.
> 
> I like the multi-line SMTP greeting, that by itself will throw a lot of lesser quality non-RFC compliant SMTP stacks for a loop.
> 
> I also like the saying that you have in the multi-line SMTP greeting.
> 
> I'll keep my fingers in my pockets while lookenpeeping.

Another trick is to NOT accept `EHLO` unless you really need TLS.  So many scripts fail to downgrade from `EHLO` to `HELO` as per RFC that it knocks out a lot of low hanging fruit cause they pipelined a bunch of commands making an assumption.

**Comment by SirWumpus** [comment]
I love my BarricadeMX, I think its one of my best works 😊😁💙 (short maybe of some code cleanup/refactoring), but it works and well.

**Comment by drscriptt** [comment]
> Another trick is to NOT accept `EHLO` ...

<ASCII scream>

I use `EHLO` for too many things other than `STARTTLS` and would miss it:

- `RCPT TO`'s `NOTIFY`
- `RCPT TO`'s `ORCPT`
- `MAIL FROM`'s `RET`
- `MAIL FROM`'s `ENVID`

Plus, I really, Really, REALLY like `STARTTLS`.  I've configured all of my systems to require encrypted channels for `AUTH`.

But, yes, I can see how not accepting `EHLO` would throw a LOT of Bad Things(TM) for a loop.

**Comment by SirWumpus** [comment]
Well BMX does support `EHLO` if you need it, but I don't think I have all those other options implemented or passed through.

**Comment by SirWumpus** [comment]
The missing file does not appear in the previous tar file.  Will appear in next release/tag.
